making the skeleton app
NycoChavanoud/atempo pull request #22
Opened 2022-05-25 15:29 UTC by ChrichriR

2022-05-26 07:25 UTC, Benjamin-Dervieux approved these changes

2022-05-30 07:34 UTC, NycoChavanoud requested changes

2022-05-30 07:34 UTC, NycoChavanoud commented on components/Layout.js
> +        <nav>
faire un component pour la navbar

2022-06-09 15:10 UTC, NycoChavanoud approved these changes

2022-06-09 15:10 UTC, merged