Profile1
NycoChavanoud/atempo pull request #26
Opened 2022-06-08 13:01 UTC by leolab69

2022-06-08 13:11 UTC, Benjamin-Dervieux approved these changes

2022-06-09 10:21 UTC, NycoChavanoud requested changes

2022-06-09 10:21 UTC, NycoChavanoud commented on pages/myProfile/index.js
> +              <br />
pas top

2022-06-10 10:09 UTC, leolab69 commented on pages/myProfile/index.js
> +// import { Widget } from "@uploadcare/react-widget";
supprimé

2022-06-10 10:09 UTC, leolab69 commented on pages/myProfile/index.js
> +              <br />
supprimé

2022-06-10 12:42 UTC, NycoChavanoud approved these changes

2022-06-10 12:42 UTC, merged